sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm install -g travis-deploy-once@6
  - travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
