sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 6
  - 8
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - if [[ $TRAVIS_NODE_VERSION -lt 7 ]]; then npm install --global npm@4; fi
before_script:
  - npm prune
script:
  - npm test
  - npm run build