sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 4
  - 6
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm test
  - npm run build