name: Tests

on: push

jobs:
    lint:
        name: Run tests
        runs-on: ubuntu-latest
        container: "node:18-alpine"
        steps:
            - uses: actions/checkout@v1
            - run: npm ci
            - run: npm test
